//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionTi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Candidatos
    {
        public int Candidatos_Id { get; set; }
        public string Candidatos_Cedula { get; set; }
        public string Candidatos_Nombre { get; set; }
        public string Candidatos_Apellido { get; set; }
        public string Candidatos_TrabajoActual { get; set; }
        public Nullable<decimal> Candidatos_ExpectativaSalarial { get; set; }
        public string Candidatos_Observaciones { get; set; }
        public DateTime Candidatos_FechaNacimiento { get; set; }
    }
}
